baseurl = "https://thanhngvpt.github.io/"
title = "Thanh's Notepad"
languageCode = "en-us"

[Params]
Author = "thanhngvpt"
disqusShortname = "thanhngvpt"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

